name: Build

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Verify native libraries
      run: dir libs\Native\Aardvark.Embree\windows\AMD64
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run: .\build.cmd
    - name: Test
      run: dotnet test src\Aardvark.Embree.sln --no-build --configuration Debug --verbosity normal
